# Usar uma imagem base do Node.js
FROM node:18

# Definir o diretório de trabalho no container
WORKDIR /usr/src/app

# Copiar o arquivo package.json e o package-lock.json (se houver)
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta do backend
EXPOSE 3000

# Comando para rodar o servidor
CMD ["node", "src/js/server.js"]
